# default configuration
baseURL = "https://davokr.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Dave Kreymerman"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

#[[menu.main]]
#URL = "portfolio"
#name = "Portfolio"
#weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#85001c"
# contact info
#phone = "+880 2544 658 256"
#email = "steve.fruits@email.com"
#address = "125/A, CA Commercial Area, California, USA"
# meta description
author = "Dave Kreymerman"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# baidu site verification
baidu_site_verification = "" #Your verification code
# baidu analytics
baidu_analytics_id = "" #Your ID
# copyright
copyright = "Copyright &copy; 2022 a website by [Dave Kreymerman](https://davokr.com)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site

[[params.social]]
icon = "fa fa-instagram"
icon2 = "ti-instagram"
URL = "https://instagram.com/davokr"

[[params.social]]
icon = "fa fa-github"
icon2 = "ti-github"
URL = "https://github.com/davokr"

[[params.social]]
icon = "fa fa-linkedin"
icon2 = "ti-linkedin"
URL = "https://www.linkedin.com/in/davokr"

[[params.social]]
icon = "fa fa-telegram"
icon2 = "ti-location-arrow"
URL = "https://www.linkedin.com/in/davokr"

#[[params.social]]
#icon = "ti-cloud-down"
#URL = "#"
