#baseURL = "https://example.com"
baseURL = "https://kreymerman.com/"
title = "Dave Kreymerman"
theme = "hugo-theme-m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "employment"
    name = "Employment"
    url = "/employment/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Dave Kreymerman"
  description = "Senior Cloud Architect"
  menu_item_separator = "|"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/davokr"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/david-kreymerman-b8662a11/"
  [[params.social]]
    icon = "instagram"
    name = "Instagram"
    url = "https://instagram.com/davokr"
  [[params.social]]
    icon = "mail"
    name = "E-Mail"
    url = "mailto:david.kreymerman@live.com"
  [[params.social]]
    icon = "send"
    name = "Telegram"
    url = "https://t.me/davokr"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  [params.style]
    darkestColor = "#642210"
    darkColor = "#373737"
    lightColor = "#d6d6d6"
    lightestColor = "#d3d3d3"
    primaryColor = "#ffffff"
